version: '3'
services:
   myapp:
      ports:
      - 8082:8082
      volumes:
        - ./config:/config
      build:
        context: .
        dockerfile: Dockerfile.app
      container_name: "app-otus-hw02"
